name: Build Kernels

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Build Env
        run: ./setup-build-env.sh
      - name: Build
        run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: kernels
          path: ~/linux-build/out/*

